#!/usr/bin/python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys
import logging

from conary.lib import util
sys.excepthook = util.genExcepthook()

from conary import versions
from conary import conarycfg
from conary import conaryclient

from rpath_repeater.utils import windows

def setupLogging():
    rootLog = logging.getLogger('')
    streamHandler = logging.StreamHandler(sys.stdout)
    streamFormatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
    streamHandler.setFormatter(streamFormatter)
    rootLog.addHandler(streamHandler)
    rootLog.setLevel(logging.DEBUG)
    return rootLog

log = setupLogging()

if len(sys.argv) != 3:
    print >>sys.stderr, 'usage: %s <host> <admin password>' % sys.argv[0]
    sys.exit(1)

user = 'Administrator'
domain = host = sys.argv[1]
password = sys.argv[2]

def status(l, p):
    print p

authInfo = windows.WindowsAuthInfo(host, domain, user, password)
system = windows.WindowsSystem(authInfo, status)

cfg = conarycfg.ConaryConfiguration(True)
cfg.readUrl('http://localhost/conaryrc')
client = conaryclient.ConaryClient(cfg)

import epdb; epdb.st()
